spring:
  application:
    name: Customers Service
    version: 0.01
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/customers
    username: minervacustomers
    password: minervacustomers
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
