services:
  #db customer
  customersdb:
    image: mariadb:latest
    container_name: minervacustomers
    ports:
      - "3307:3306"
    restart: always
    environment:
      MARIADB_USER: minervacustomers
      MARIADB_PASSWORD: minervacustomers
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: minervacustomers
    networks:
      - mincustomers
    #customer
  customers:
    container_name: minerva-customers-micro
    image: matteo29mar/minervacustomers:1.4
    ports:
      - "8080:8080"
    networks:
      - mincustomers
    depends_on:
      - customersdb
    #borrowing
  borrowing:
    container_name: minerva-borrowing-micro
    image: elisacg/borrowing
    ports:
      - "8080:8080"
    networks:
      - minborrowing
    depends_on:
      - borrowingdb

  #borrowing db
  borrowingdb:
    image: mongo:latest
    container_name: minervaborrowing
    ports:
      - "27017:27018"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: E2Lge3zczAvjQ61f
      MONGO_INITDB_DATABASE: Borrowing
    volumes:
      - mongodb_data:/data/db
    networks:
      - minborrowing

  #booksdb
  minerva-books-db:
    image: mariadb:latest
    container_name: minervabooks
    ports:
      - "3307:3306"
    restart: always
    environment:
      MARIADB_USER: uttsadmin
      MARIADB_PASSWORD: appsistutt@admin#
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: minerva-books-db
    networks:
      - minbooks
    #rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=minervabooks
      - RABBITMQ_DEFAULT_PASS=minervabooks@notify#
  #prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
networks:
      mincustomers:
      minborrowing:

volumes:
        mongodb_data: {}