spring:
    main:
        web-application-type: none
    application:
        name: Books Service
        version: 0.01

rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    username: minervanotify
    password: @notify

minerva:
    rabbitmq:
        queue: minervaqueue