FROM maven:3-openjdk-17-slim as builder
COPY Customers/src /home/app/src
COPY Customers/pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:17
COPY --from=builder /app/src/Customers/target/*.jar Customers.jar
EXPOSE 8102
ENTRYPOINT ["java","-jar","Customers.jar"]
