FROM maven:3-openjdk-17-slim as builder
COPY Customers/src/ /app/src/Customers
COPY Customers/pom.xml /app/src/Customers
RUN mvn -f /app/src/Customers/pom.xml clean package

FROM openjdk:17
COPY --from=builder /app/src/Customers/target/*.jar Customers.jar
EXPOSE 8102
ENTRYPOINT ["java","-jar","Customers.jar"]
