server:
    port: 9011
    error:
      include-stacktrace: never
      whitelabel:
        enabled: false
    servlet:
      context-path: /minerva/books

springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui



spring:
  output:
    ansi:
      enabled: always
  application:
    name: Books Service
    version: 0.01
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3609/appsist
    username: uttsadmin
    password: appsistutts@admin#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: static/banner/minervabooks.txt
  rabbitmq:
    host: 192.168.1.222
    virtual-host: /
    port: 5672
    username: minervabooks
    password: minervabooks@notify#
  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      springframework: error
    com:
      minerva: trace
  pattern:
    console: "%d{HH:mm:SSS} [%t] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus