application:
  title: Books Service
  version: 0.1
spring:
  server:
    port: 9001
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/minervabooks
    username: minervabooks
    password: minervabooks@admin#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: static/banner/minervabooks.txt