server:
    port: 9011
    error:
      include-stacktrace: never
      whitelabel:
        enabled: false

spring:
  application:
    name: Books Service
    version: 0.01
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/minervabooks
    username: minervabooks
    password: minervabooks@admin#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: static/banner/minervabooks.txt
  rabbitmq:
    host: 192.168.1.222
    virtual-host: /
    port: 5672
    stream:
      username: minervabooks
      password: minervabooks@notify#
  web:
    resources:
      add-mappings: false
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus