application:
  title: Books Service
  version: 0.1
server:
    port: 9001
    error:
      include-stacktrace: never
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/minervabooks
    username: minervabooks
    password: minervabooks@admin#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: static/banner/minervabooks.txt
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus