spring:
  application:
    name: Customers Service
    version: 0.01
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driverClassName: org.postgresql.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/customers
    username: customer
    password: customer@admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
