name: Minerva CI/CD

on:
  push:
    branches: [feature/Books]
  pull_request:
    branches: [feature/Books]

jobs:
  books-micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/Books
      - name: list files
        run: ls -l
      - name: Login to Docker Hub for books microservice
        uses: docker/login-action@v2
        with:
          username: imnotikeatits
          password: Ett0r317#@
      - name: Build and push books microservice docker image
        uses: docker/build-push-action@v3
        with:
          file: "Books/books/docker/Dockerfile"
          push: true
          tags: imnotikeatits/minerva-books:${{github.run_number}}
