name: Build and publish Books microservice Docker Image

on:
  push:
    branches: [feature/Books]
  pull_request:
    branches: [feature/Books]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imnotikeatits
          password: Ett0r317#@
      - name:
        uses: docker/build-push-action@v3
        with:
          context: ./Books/books/docker/
          push: true
          tags: imnotikeatits/minerva-books:${{github.run_number}}
