name: Books CI/CD

on:
  push:
    branches: [feature/Books]
  pull_request:
    branches: [feature/Books]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn clean package --file ./Books/books/pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: minerva-books
          path: ./Books/books/target/books-0.0.1-SNAPSHOT.jar
      - name: Set up QEMU for books microservice
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download JAR
          uses: actions/download-artifact@v2
          with:
            name: minerva-books
            path: ./target
      - name: Login to Docker Hub for books microservice
        uses: docker/login-action@v2
        with:
          username: imnotikeatits
          password: Ett0r317#@
      - name: Build and push books microservice docker image
        uses: docker/build-push-action@v3
        with:
          file: "Books/books/Dockerfile"
          push: true
          tags: imnotikeatits/minerva-books:${{github.run_number}}
